export const presentation = [
 {title:'Meet Maya',cue:'A CS student with classes, habits, and a full campus day.',seconds:10,kind:'profile'},
 {title:'Her whole week',cue:'Classes, gym sessions, and events live in one connected plan.',seconds:10,kind:'week'},
 {title:'Leave residence',cue:'WATWay resolves the classroom and calculates when Maya should leave.',seconds:12,kind:'chapter',chapter:0},
 {title:'A* finds the route',cue:'These are real search results from the campus graph.',seconds:12,kind:'engine',stage:0},
 {title:'Dry-weather baseline',cue:'Start with a dry day. Watch the route and covered percentage.',seconds:8,kind:'engine',stage:1,dry:true},
 {title:'Winter changes the decision',cue:'Snow increases outdoor costs and favors protected paths.',seconds:12,kind:'engine',stage:1},
 {title:'The network bottleneck',cue:'Constrain one bridge: maximum flow falls from 60 to 16 people per minute.',seconds:14,kind:'engine',stage:2},
 {title:'Class-change traffic',cue:'Demand changes with the timetable, adding delays to busy connections.',seconds:12,kind:'engine',stage:3},
 {title:'Find the classroom in first person',cue:'A simple straight hallway, staircase, and hallway. Demonstrating movement and wall collisions.',seconds:60,kind:'interior'},
 {title:'Coffee between classes',cue:'The next useful stop fits Maya’s schedule and her location.',seconds:10,kind:'chapter',chapter:1},
 {title:'Lunch, then lab',cue:'The plan moves naturally from class to lunch and the afternoon lab.',seconds:10,kind:'chapter',chapter:2},
 {title:'A quiet study gap',cue:'Davis Library fits the gap before her regular workout.',seconds:10,kind:'chapter',chapter:3},
 {title:'Time for the gym',cue:'Maya’s PAC habit is part of the day, alongside campus activity estimates.',seconds:12,kind:'chapter',chapter:4},
 {title:'Discover campus events',cue:'A selected Luma event becomes the next destination after the workout.',seconds:12,kind:'chapter',chapter:5},
 {title:'Protected indoor walking',cue:'A simplified indoor walkthrough: connected surfaces, solid walls, and no turns.',seconds:60,kind:'walk'},
 {title:'Cowork, then head home',cue:'WYGO coworking rounds out the evening. The whole day stays connected.',seconds:12,kind:'chapter',chapter:7},
 {title:'One campus. One connected day.',cue:'Classes, weather, traffic, habits, and events—working together for Maya.',seconds:10,kind:'chapter',chapter:8},
] as const;
